chief/urls.py
from django.conf.urls import patterns, include, url
from recipe.views import RecipeDetailView, RecipeCategoryListView, HotRecipeListView, DidRecipeDetailView
from food.views import FoodDetailView, FoodCategoryDetailView
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',   
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^comments/post/$', 'recipe.ajax_comment_post.post_comment', name='ajaxcommentpost'),
    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       'accounts.views.profile',
       name='userena_profile_detail'),
    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/message/$',
       'accounts.views.leave_message',
       name='leave_message'),
    url(r'^accounts/(?P<username>[\.\w]+)/edit/$',
       'accounts.views.profile_edit',
       name='userena_profile_edit'),

    url(r'^message_comet/$', 'accounts.views.message_comet', name='message_comet'),

    url(r'^accounts/', include('userena.urls')),

    url(r'^messages/', include('userena.contrib.umessages.urls')),

    url(r'^grappelli/', include('grappelli.urls')),
    #url(r'^$', 'recipe.views.nav', name='homepage'),
	url(r'^$', 'recipe.views.index', name='homepage'),

    # URL for recipe
    url(r'^recipe/add/$', 'recipe.views.recipe_create', name='recipe_create'),
    url(r'^recipe/(?P<pk>\d+)/$', RecipeDetailView.as_view(), name='recipe_detail'),
    url(r'^recipe/(?P<pk>\d+)/rate/$', 'recipe.views.rate', name='rate'),
    url(r'^recipe/(?P<pk>\d+)/like/$', 'recipe.views.like', name='like'),
    url(r'^recipe/(?P<pk>\d+)/unlike/$', 'recipe.views.unlike', name='unlike'),
    url(r'^recipe/(?P<pk>\d+)/edit/$', 'recipe.views.recipe_edit', name='recipe_edit'),
    url(r'^recipe/(?P<pk>\d+)/delete/$', 'recipe.views.recipe_delete', name='recipe_delete'),
    url(r'^recipe/(?P<pk>\d+)/did/$', 'recipe.views.did_recipe_upload', name='did_recipe_upload'),
    url(r'^didrecipe/(?P<pk>\d+)/$', DidRecipeDetailView.as_view(), name='did_recipe_detail'),

    url(r'^recipecategory/(\d+)/(hot|time|trend|rating)/$', RecipeCategoryListView.as_view(), name='recipe_category'),
    url(r'^hot/$', HotRecipeListView.as_view(), name='hot_recipes'),
    url(r'^recipe/cover_image_upload/$', 'recipe.views.cover_image_upload', name='recipe_image_upload'),
    url(r'^recipe/step_image_upload/$', 'recipe.views.step_image_upload', name='step_image_upload'),

    # URL for food
    url(r'^food/(?P<pk>\d+)/$', FoodDetailView.as_view(), name='food_detail'),
    url(r'^foodcategory/(?P<pk>\d+)/$', FoodCategoryDetailView.as_view(), name='food_list'),
    url(r'^categories/$', 'food.views.categories', name='categories'),


    # URL for activity
    url(r'^activity/$', 'accounts.views.activity', name='actstream'),
    url(r'^activity/', include('actstream.urls')),

    url(r'^ajax/image_delete/$', 'recipe.views.image_delete', name='image_delete'),

    # URL for search
    url(r'^search/autonav/$', 'recipe.search.autonav', name='autonav'),
    url(r'^search/$', 'recipe.search.normal_search', name='normal_search'),
    url(r'^search/advanced/$', 'recipe.search.advanced_search', name = 'advanced_search'),


    # URL for shopping
    url(r'shopping/add/$', 'shopping.views.add_item', name='add_to_shopping_list'),
    url(r'shopping/list/$', 'shopping.views.view_shopping_list', name='view_shopping_list')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from food.models import Food
from imagekit.models.fields import ProcessedImageField
from imagekit.processors import ResizeToFit, Adjust
from django.core.validators import MaxValueValidator
import os
import uuid

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('Recipe_photos', filename)

def did_get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('DidRecipe_photos', filename)


class RecipeCategory(models.Model):
	"""docstring for RecipeCategory"""

	name = models.CharField(max_length=200)
	brief = models.TextField(blank=True)
	parent = models.ForeignKey('self', null=True, blank=True)

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('recipe_category', (self.id, 'hot'))


class Recipe(models.Model):
	"""docstring for Recipe"""

	name = models.CharField(db_index=True, max_length=200)
	author = models.ForeignKey(User)
	date = models.DateField(auto_now_add=True)
	category = models.ManyToManyField(RecipeCategory, verbose_name=u'list of categories')
	brief = models.TextField()
	ingredients = models.ManyToManyField(Food, through='Amount', verbose_name=u"list of ingredients")

	cover_image = ProcessedImageField(upload_to=get_file_path, null=True, blank=True, verbose_name=u'Cover image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 90})

	tips = models.TextField(blank=True)
	did_num = models.PositiveIntegerField(default=0)
	like_num = models.PositiveIntegerField(default=0)
	view_num = models.PositiveIntegerField(default=0)
	trend_num = models.FloatField(default=0.0)
	today_view_num = models.PositiveIntegerField(default=0)

	prep_time = models.TimeField()
	cook_time = models.TimeField()

	cumulative_score = models.IntegerField(default=0)
	rating_num = models.IntegerField(default=0)

	def rating(self):
		result = float(self.cumulative_score)
		if self.rating_num == 0:
			return "0.0"
		result = result/self.rating_num
		return "%g" % round(result, 1)

	def rating_int(self):
		result = float(self.cumulative_score)
		if self.rating_num == 0:
			return 0
		result = result/self.rating_num
		return int(round(result))

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('recipe_detail', (), {'pk': self.id})

	class Meta:
		ordering = ['-view_num', '-like_num']


class DidRecipe(models.Model):
	"""docstring for DidRecipe"""
	recipe = models.ForeignKey(Recipe)
	user = models.ForeignKey(User)
	image = ProcessedImageField(upload_to=did_get_file_path, null=True, blank=True, verbose_name=u'Cover image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 90})
	comment = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return u"%s's %s" % (self.user.username, self.recipe.name)

	@models.permalink
	def get_absolute_url(self):
		return ('did_recipe_detail', (), {'pk': self.id})

	class Meta:
		ordering = ['recipe', '-date']

class Amount(models.Model):
	"""docstring for Amount"""
	
	ingredient = models.ForeignKey(Food)
	recipe = models.ForeignKey(Recipe)
	amount = models.CharField(max_length=50)
	must = models.BooleanField(default=False)

	def __unicode__(self):
		return u'Amount of %s in %s' % (self.ingredient.name, self.recipe.name)

	class Meta:
		ordering = ['recipe','-must']
		unique_together = ('recipe', 'ingredient')
		
class Step(models.Model):
	"""docstring for Steps"""

	recipe = models.ForeignKey(Recipe)
	step_num = models.PositiveIntegerField()
	description = models.CharField(max_length = 1000)
	step_image = ProcessedImageField(upload_to=get_file_path, null=True, blank=True, verbose_name=u'Step image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 80})

	def __unicode__(self):
		return u'Step %d of %s' % (self.step_num, self.recipe.name)

	class Meta:
		ordering = ['recipe', 'step_num']
		unique_together = ("recipe", "step_num")

class Vote(models.Model):
	"""Vote class, used for recommendation system """
	recipe = models.ForeignKey(Recipe)
	user = models.ForeignKey(User)
	score = models.PositiveSmallIntegerField(validators=[MaxValueValidator(5)])
	comment = models.TextField()
	date = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return u'Vote for %s from %s' %(self.recipe.name, self.user)

	class Meta:
		ordering = ['user', 'recipe',]
		unique_together = ("user", "recipe")

recipe/forms.py
from django.forms import ModelForm
from recipe.models import Recipe, Step, Vote, DidRecipe, RecipeCategory
from django.forms.models import inlineformset_factory
from django import forms
from django.conf import settings
import os
import sys

class DidRecipeForm(ModelForm):
	class Meta:
		model = DidRecipe
		exclude = ('date', )
		widgets = {
			'recipe': forms.HiddenInput(),
			'user': forms.HiddenInput(),
		}

class RecipeForm(ModelForm):
	prep_time = forms.TimeField(input_formats=['%H:%M','%H:%M:%S',])
	cook_time = forms.TimeField(input_formats=['%H:%M','%H:%M:%S',])
	cover_image = forms.CharField(widget=forms.HiddenInput(), required=False)
	class Meta:
		model = Recipe
		fields = ('name', 'author', 'category', 'brief', 'cover_image', 'tips', 'prep_time', 'cook_time')
		widgets = {
			'author': forms.HiddenInput(),
		}

class VoteForm(forms.Form):
	score = forms.IntegerField(min_value = 0, max_value = 5)
	comment = forms.CharField(widget=forms.Textarea, required=False)

class StepForm(forms.Form):
	description = forms.CharField(widget=forms.Textarea(), min_length = 1)
	step_image = forms.CharField(widget=forms.HiddenInput(), required=False)

class AmountForm(forms.Form):
	ingredient = forms.CharField(min_length = 1)
	amount = forms.CharField(min_length = 1)
	must = forms.BooleanField(required=False)

class SearchForm(forms.Form):
	ingredient = forms.CharField(min_length = 1)


MIN_RATING_CHOICES=(
	('0', '0'),
	('1', '1'),
	('2', '2'),
	('3', '3'),
	('4', '4'),
	('5', '5'),
)
COURSES_CHOICES =[('0', 'None'),] + [ (obj.id, obj.name) for obj in list(RecipeCategory.objects.filter(parent__name='Courses').only('name'))]
CUISINES_CHOICES =[('0', 'None'),] + [ (obj.id, obj.name) for obj in list(RecipeCategory.objects.filter(parent__name='Cuisines').only('name'))]
INGREDIENTS_CHOICES =[('0', 'None'),] + [ (obj.id, obj.name) for obj in list(RecipeCategory.objects.filter(parent__name='Main Ingredients').only('name'))]
DIETS_CHOICES =[('0', 'None'),] + [ (obj.id, obj.name) for obj in list(RecipeCategory.objects.filter(parent__name='Special Diets').only('name'))]

class SearchFormExtra(forms.Form):
	courses = forms.ChoiceField(choices=COURSES_CHOICES)
	cuisines = forms.ChoiceField(choices=CUISINES_CHOICES)
	main_ingredients = forms.ChoiceField(choices=INGREDIENTS_CHOICES)
	special_diets = forms.ChoiceField(choices=DIETS_CHOICES)
	min_rating = forms.ChoiceField(choices=MIN_RATING_CHOICES)

templates/recipe/advanced_search.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}
Advanced Search
{% endblock%}

{% block content %}
<div class="row">
<form id="search_form" method="POST" action="">
	{% csrf_token %}
	<legend>Advanced Search</legend>
	<div>
		<h2>Find Recipes with your ingredients...</h2>
		<table border="0" cellpadding="0" cellspacing="0">
			<tbody>
				{% for form in formset.forms %}
				<tr>
					<th>Ingredient: <th>
					<td>{{ form.ingredient }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
	<div>
		<h2>Then narrow your result by...</h2>
		<table>
			<tbody>
				{% for field in extra_form%}
				<tr>
					<th>
						{{field.label}}
					</th>
					<td>
						{{field}}
					</td>	
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<button class="btn" type="submit">Search</button>
	{{ formset.management_form }}
</form>
{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static "js/jquery.formset.min.js" %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function (){
		jQuery('#search_form tbody tr').formset({
			prefix: '{{ formset.prefix }}',
			addText: 'Add another ingredient that you have',
			added: function(row){
				row.find('a').attr('tabindex', '-1');
				row.find(':text').attr('autocomplete', 'off');
				row.find(':text').typeahead({
					source: [{% for food in food_name_list%}"{{food.name}}",{% endfor %}],
					items: 4,
				});
			},
		});
		jQuery('a').attr('tabindex', '-1');
		jQuery(':text').attr('autocomplete', 'off');
		jQuery(':text').attr('data-provide','typeahead');
		jQuery(':text').typeahead({
			source: [{% for food in food_name_list%}"{{food.name}}",{% endfor %}],
			items: 4,
		});
	});
</script>
{% endblock js %}

templates/recipe/comment.html
{% load thumbnail %}
<div>
	<img src="{{comment.user.get_profile.mugshot|thumbnail_url:'avatar'}}" />
	<a href="{{comment.user.get_absolute_url}}">{{comment.user}}</a>:
	{{comment.comment}}
	{{comment.submit_date|timesince}} ago
</div>

templates/recipe/recipe_form.html
<!-- recipe_form.html -->
{% extends 'nav.html' %}

{% load i18n %}
{% load url from future %}
{% load static %}

{% block title%}
Upload your Recipe
{% endblock title%}

{% block csslink %}
{{block.super}}
<link rel="stylesheet" type="text/css" href="{% static "css/timepicker.css" %}">
<link href="{{ STATIC_URL }}ajaxuploader/css/fileuploader.css" media="screen" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static "css/recipe/recipe_form.css" %}"/>
<link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates:400,700' rel='stylesheet' type='text/css'>
{% endblock csslink %}

{% block content %}
<form id="newFormsets" method="post" enctype="multipart/form-data" action="" class="well well-small">
  {% csrf_token %}
<fieldset>
  <legend>Create a recipe</legend>  
  <table id="recipe_table" class="container span12">
    <thead style="display:none;">
      <th>Form Name</th>
      <th>Form Content</th>
    </thead>
    <tbody class="row-fluid">
      <tr class="span12" style="margin-left:20px;">
        <td class="form-label span2">{{recipe_form.name.label}}</td>
        <td class="offset1 span8">{{recipe_form.name}}
          <span class="help-inline">{% for error in recipe_form.name.errors %}{{ error|escape }}{% endfor %}
          </span></td>
      </tr>
      {{recipe_form.author}}
      {{recipe_form.category}}
      <tr class="span12">
        <td class="form-label span2">Courses</td>
        <td class="offset1 span8">
          <select class="seperated_select">
            <option>None</option>
            {% for c in Courses%}
            {% if c in category_list %}
            <option value="{{c.id}}" selected>{{c.name}}</option>
            {% else %}
            <option value="{{c.id}}">{{c.name}}</option>
            {% endif %}
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Cuisine</td>
        <td class="offset1 span8">
          <select class="seperated_select">
            <option>None</option>
            {% for c in Cuisines%}
            {% if c in category_list %}
            <option value="{{c.id}}" selected>{{c.name}}</option>
            {% else %}
            <option value="{{c.id}}">{{c.name}}</option>
            {% endif %}
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Main Ingredient</td>
        <td class="offset1 span8">
          <select class="seperated_select">
            <option>None</option>
            {% for c in Main_Ingredients%}
            {% if c in category_list %}
            <option value="{{c.id}}" selected>{{c.name}}</option>
            {% else %}
            <option value="{{c.id}}">{{c.name}}</option>
            {% endif %}
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Special Diet</td>
        <td class="offset1 span8">
          <select class="seperated_select">
            <option>None</option>
            {% for c in Special_Diets%}
            {% if c in category_list %}
            <option value="{{c.id}}" selected>{{c.name}}</option>
            {% else %}
            <option value="{{c.id}}">{{c.name}}</option>
            {% endif %}
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">{{recipe_form.brief.label}}</td>
        <td class="offset1 span8">{{recipe_form.brief}}<span class="help-inline">{% for error in recipe_form.brief.errors %}{{ error|escape }}{% endfor %}
          </span></td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Cover Image</td>
        <td class="offset1 span8">
          <div id="cover_image_frame">
            <img id="cover_image_preview" />{{recipe_form.cover_image}}
            <div id="recipe_uploader"></div>
            <button class="btn" id="cover_image_delete">X</button>
          </div>
        </td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Notes</td>
        <td class="offset1 span8">{{recipe_form.tips}}<span class="help-inline">{% for error in recipe_form.tips.errors %}{{ error|escape }}{% endfor %}
          </span></td>
      </tr>
      <tr class="span12">
        <td class="form-label span2">Preparation Time</td>
        <td class="offset1 span8">
          <div class="input-append bootstrap-timepicker-component">
            <input type="text" class="timepicker-default input-small" name="prep_time" value="{{recipe_form.prep_time.value}}">
            <span class="add-on">
                <i class="icon-time"></i>
            </span>
          </div>
          <span class="help-inline">{% for error in recipe_form.cook_time.errors %}{{ error|escape }}{% endfor %}
          </span></td>
      </tr class="span12">
      <tr class="span12">
        <td class="form-label span2">Cook Time</td>
        <td class="offset1 span8">
          <div class="input-append bootstrap-timepicker-component">
            <input type="text" class="timepicker-default input-small" name="cook_time" value="{{recipe_form.cook_time.value}}">
            <span class="add-on">
                <i class="icon-time"></i>
            </span>
          </div>
          <span class="help-inline">{% for error in recipe_form.cook_time.errors %}{{ error|escape }}{% endfor %}
          </span></td>
      </tr>
    </tbody>
  </table>
</fieldset>

<fieldset id="mod-ingredient">
<legend>How about the ingredients?</legend>  
{{ amount_formset.management_form }}
<table id="ingredient_table"> 
  <thead class="row-fluid">
    <tr>
      <th><div class="span6">Ingredient</div></th>
      <th><div class="span3">Amount</div></th>
      <th><div class="offset2 span3">Must?</div></th>
    </tr>
  </thead>    
  <tbody class="row-fluid">
    {% for form in amount_formset %}
    <tr>{{ form.recipe }}
      <td><div class="span6 ingredient_type">{{ form.ingredient }}</div></td>
      <td><div class="span3 mini">{{ form.amount }}</div></td>
      <td><div class="offset2 span3">{{ form.must }}</div></td>
    </tr>
    {% endfor %}
  </tbody> 
</table>
</fieldset>
<fieldset id="mod-step">
<legend>Wanna share your cooking steps with us?</legend>
{{ step_formset.management_form }}
<table id="step_table" class="">
  <thead>
    <tr>
      <th><div class="span1">Step Num</div></th>
      <th><div class="span3">Step Description</div></th>
      <th><div class="span3">Step Image</div></th>
    </tr>
  </thead>
  <tbody>
    {% for form in step_formset %}
    <tr>{{form.recipe}}
      <td><div class="step_num_counter span1"></div></td>
      <td><div class="span3">{{ form.description }}</div></td>
      <td>
        <div class="step_image_frame span3">{{ form.step_image }}
          <img class="step_preview" id="step{{forloop.counter0}}_preview" />
          <div class="step-uploader"></div>
          <button class="btn step_image_delete">X</button>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody> 
</table>
</fieldset>
<button type="submit" id="save_button" class="btn btn-primary pull-right">Save</button>

</form>
{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static "js/jquery.formset.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootstrap-timepicker.js" %}"></script>

<script src="{{ STATIC_URL }}ajaxuploader/js/fileuploader.js" ></script>  
<script type="text/javascript" src="{% static "js/recipe/recipe_form.js" %}"></script>
<script type="text/javascript">
function bindSelet(){
  var l = new Array();
  $('.seperated_select').each(function (i){
    if ($(this).val()!='None'){
      l.push($(this).val());
    }
  });
  $('#id_category').val(l);
}

$('body').on('click', '.step_image_delete', function(event) {
  event.preventDefault();
  var del = $(event.target);
  var preview  = $(event.target).siblings('img');
  var input = $(event.target).siblings('input');
  var up = $(event.target).siblings('.step-uploader');
  var url = '{% url "image_delete"%}';
  var postdata = {
    'file': $(input).val(),
    'csrfmiddlewaretoken': '{{ csrf_token }}',
  }

  $.post(url, postdata, function(data){
    if (data=='success'){
      $(del).hide();
      $(preview).attr('src','');
      $(preview).hide('slow');
      $(input).val('');
      $(up).show();
    }
  });
});

$(document).ready(function() {
  $('#ingredient_table tbody tr').formset({
    prefix: '{{ amount_formset.prefix }}',
    formCssClass: 'dynamic_amount_formset',
    added: function(row){
      row.find('td > div.mini > input').addClass('input-mini');
      row.find('a').attr('tabindex', '-1');
      row.find('.ingredient_type').find('input').attr('autocomplete', 'off');
      row.find('.ingredient_type').find('input').typeahead({
        source: [{% for food in food_name_list%}"{{food.name}}",{% endfor %}],
        items: 4,
      });
    },
  });

  $('#step_table tbody tr').formset({
    prefix: '{{ step_formset.prefix }}',
    formCssClass: 'dynamic_step_formset',
    removed: function(row){
      stepCount(jQuery('.step_num_counter'));
    },
    added: function(row) {
      stepCount(jQuery('.step_num_counter'));
      var uploader1 = new qq.FileUploader({
        action: "{% url 'step_image_upload' %}",
        element: row.find('.step-uploader')[0],
        multiple: false,
        onComplete: function(id, fileName, responseJSON) {
          if(responseJSON.success) {
            row.find('[id*="step_image"]').val(responseJSON.path);
            row.find('.step_preview').attr('src', '/media/'+responseJSON.path);
            row.find('.step_image_delete').show();
            row.find('.step-uploader').hide();
            row.find('.step_preview').show('slow');
            $('.qq-upload-list').css('display','none');
          } else {
            alert("upload failed!");
          }
        },
        params: {
          'csrf_token': '{{ csrf_token }}',
          'csrf_name': 'csrfmiddlewaretoken',
          'csrf_xname': 'X-CSRFToken',
        },
      });
    },
  });

  jQuery('a.delete-row').attr('tabindex', '-1');
  jQuery('#ingredient_table').find('.ingredient_type').find(':text').attr('autocomplete', 'off');
  jQuery('#ingredient_table').find('.ingredient_type').find(':text').attr('data-provide','typeahead');
  jQuery('#ingredient_table').find('.ingredient_type').find(':text').typeahead({
      source: [{% for food in food_name_list%}"{{food.name}}",{% endfor %}],
      items: 4,
    });

  $('.timepicker-default').timepicker({
    minuteStep: 10,
    defaultTime: '01:00',
    showMeridian: false,
  });
  $('#id_category').hide();
  $('.seperated_select').change(function (){
    bindSelet();
  });

  stepCount(jQuery('.step_num_counter'));

  $('#cover_image_delete').click(function (event) {
    event.preventDefault();
    var url = '{% url "image_delete"%}'
    var postdata = {
      'file': $('#id_cover_image').val(),
      'csrfmiddlewaretoken': '{{ csrf_token }}',
    }
    $.post(url, postdata, function(data){
      if (data=='success'){
        $('#cover_image_delete').hide();
        $('#cover_image_preview').attr('src','');
        $('#cover_image_preview').hide('slow');
        $('#id_cover_image').val('');
        $('#recipe_uploader').show();
      }
    });
  });

  if($('#id_cover_image').val()){
    $('#cover_image_preview').attr(
      'src','/media/'+ $('#id_cover_image').val()
    );
    $('#recipe_uploader').hide();
    $('#cover_image_delete').show();
  }
  
  $('.step_preview').each(function (i){
    if($('#id_step-'+i+'-step_image').val()){
      $('#step'+i+'_preview').attr('src',
        $('#id_step-'+i+'-step_image').val());
      $($('.step_image_delete').get(i)).show();
      $($('.step-uploader').get(i)).hide();
    }
    
  });

 $('.step-uploader').each(function (i){
  var sd = $('.step_image_delete').get(i),
      su = $('.step-uploader').get(i),
      preview = $('.step_preview').get(i);
  var uploader2 = new qq.FileUploader({
    action: "{% url 'step_image_upload' %}",
    element: $('.step-uploader')[i],
    multiple: false,
    onComplete: function(id, fileName, responseJSON) {
      if(responseJSON.success) {
        $('#id_step-'+i+'-step_image').val(responseJSON.path);
        $('#step'+i+'_preview').attr('src', '/media/'+responseJSON.path);
        $(sd).show();
        $(su).hide();
        $(preview).show('slow');
        $('.qq-upload-list').css('display','none');
      } else {
        alert("upload failed!");
      }
    },
    params: {
      'csrf_token': '{{ csrf_token }}',
      'csrf_name': 'csrfmiddlewaretoken',
      'csrf_xname': 'X-CSRFToken',
    },
  });
});


 var uploader = new qq.FileUploader({
  action: "{% url 'recipe_image_upload' %}",
  element: $('#recipe_uploader')[0],
  multiple: false,
  onComplete: function(id, fileName, responseJSON) {
    if(responseJSON.success) {
      $('#id_cover_image').val(responseJSON.path);
      $('#cover_image_preview').attr('src', '/media/'+responseJSON.path);

      $('.qq-upload-list').css('display','none');
      $('#cover_image_delete').show();
      $('#cover_image_preview').show('slow');
      $('#recipe_uploader').hide();
    } else {
      alert("upload failed!");
    }
  },
  params: {
    'csrf_token': '{{ csrf_token }}',
    'csrf_name': 'csrfmiddlewaretoken',
    'csrf_xname': 'X-CSRFToken',
  },
});
});

$(document).ready(function () {
  $('td > div.mini > input').addClass('input-mini');

  var $content = $('a.delete-row').html();
  $content = '<i class="icon-trash"></i> ' + $content;
  $('a.delete-row').html($content);

  $content = $('a.add-row').html();
  $content = '<i class="icon-plus-sign"></i> ' + $content;
  $('a.add-row').html($content);
});
</script>
{% endblock js%}