chief/urls.py
from django.conf.urls import patterns, include, url
from recipe.views import RecipeDetailView, RecipeCategoryListView, HotRecipeListView, DidRecipeDetailView
from food.views import FoodDetailView, FoodCategoryDetailView
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',   
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^comments/post/$', 'recipe.ajax_comment_post.post_comment', name='ajaxcommentpost'),
    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/$',
       'accounts.views.profile',
       name='userena_profile_detail'),
    url(r'^accounts/(?P<username>(?!signout|signup|signin)[\.\w]+)/message/$',
       'accounts.views.leave_message',
       name='leave_message'),
    url(r'^accounts/(?P<username>[\.\w]+)/edit/$',
       'accounts.views.profile_edit',
       name='userena_profile_edit'),

    url(r'^message_comet/$', 'accounts.views.message_comet', name='message_comet'),

    url(r'^accounts/', include('userena.urls')),

    url(r'^messages/', include('userena.contrib.umessages.urls')),

    url(r'^grappelli/', include('grappelli.urls')),
    #url(r'^$', 'recipe.views.nav', name='homepage'),
	url(r'^$', 'recipe.views.index', name='homepage'),

    # URL for recipe
    url(r'^recipe/add/$', 'recipe.views.recipe_create', name='recipe_create'),
    url(r'^recipe/(?P<pk>\d+)/$', RecipeDetailView.as_view(), name='recipe_detail'),
    url(r'^recipe/(?P<pk>\d+)/rate/$', 'recipe.views.rate', name='rate'),
    url(r'^recipe/(?P<pk>\d+)/like/$', 'recipe.views.like', name='like'),
    url(r'^recipe/(?P<pk>\d+)/unlike/$', 'recipe.views.unlike', name='unlike'),
    url(r'^recipe/(?P<pk>\d+)/edit/$', 'recipe.views.recipe_edit', name='recipe_edit'),
    url(r'^recipe/(?P<pk>\d+)/delete/$', 'recipe.views.recipe_delete', name='recipe_delete'),
    url(r'^recipe/(?P<pk>\d+)/did/$', 'recipe.views.did_recipe_upload', name='did_recipe_upload'),
    url(r'^didrecipe/(?P<pk>\d+)/$', DidRecipeDetailView.as_view(), name='did_recipe_detail'),

    url(r'^recipecategory/(\d+)/(hot|time|trend|rating)/$', RecipeCategoryListView.as_view(), name='recipe_category'),
    url(r'^hot/$', HotRecipeListView.as_view(), name='hot_recipes'),
    url(r'^recipe/cover_image_upload/$', 'recipe.views.cover_image_upload', name='recipe_image_upload'),
    url(r'^recipe/step_image_upload/$', 'recipe.views.step_image_upload', name='step_image_upload'),

    # URL for food
    url(r'^food/(?P<pk>\d+)/$', FoodDetailView.as_view(), name='food_detail'),
    url(r'^foodcategory/(?P<pk>\d+)/$', FoodCategoryDetailView.as_view(), name='food_list'),
    url(r'^categories/$', 'food.views.categories', name='categories'),


    # URL for activity
    url(r'^activity/$', 'accounts.views.activity', name='actstream'),
    url(r'^activity/', include('actstream.urls')),

    url(r'^ajax/image_delete/$', 'recipe.views.image_delete', name='image_delete'),

    # URL for search
    url(r'^search/autonav/$', 'recipe.search.autonav', name='autonav'),
    url(r'^search/$', 'recipe.search.normal_search', name='normal_search'),
    url(r'^search/advanced/$', 'recipe.search.advanced_search', name = 'advanced_search'),


    # URL for shopping
    url(r'shopping/add/$', 'shopping.views.add_item', name='add_to_shopping_list'),
    url(r'shopping/list/$', 'shopping.views.view_shopping_list', name='view_shopping_list')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from food.models import Food
from imagekit.models.fields import ProcessedImageField
from imagekit.processors import ResizeToFit, Adjust
from django.core.validators import MaxValueValidator
import os
import uuid

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('Recipe_photos', filename)

def did_get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('DidRecipe_photos', filename)


class RecipeCategory(models.Model):
	"""docstring for RecipeCategory"""

	name = models.CharField(max_length=200)
	brief = models.TextField(blank=True)
	parent = models.ForeignKey('self', null=True, blank=True)

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('recipe_category', (self.id, 'hot'))


class Recipe(models.Model):
	"""docstring for Recipe"""

	name = models.CharField(db_index=True, max_length=200)
	author = models.ForeignKey(User)
	date = models.DateField(auto_now_add=True)
	category = models.ManyToManyField(RecipeCategory, verbose_name=u'list of categories')
	brief = models.TextField()
	ingredients = models.ManyToManyField(Food, through='Amount', verbose_name=u"list of ingredients")

	cover_image = ProcessedImageField(upload_to=get_file_path, null=True, blank=True, verbose_name=u'Cover image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 90})

	tips = models.TextField(blank=True)
	did_num = models.PositiveIntegerField(default=0)
	like_num = models.PositiveIntegerField(default=0)
	view_num = models.PositiveIntegerField(default=0)
	trend_num = models.FloatField(default=0.0)
	today_view_num = models.PositiveIntegerField(default=0)

	prep_time = models.TimeField()
	cook_time = models.TimeField()

	cumulative_score = models.IntegerField(default=0)
	rating_num = models.IntegerField(default=0)

	def rating(self):
		result = float(self.cumulative_score)
		if self.rating_num == 0:
			return "0.0"
		result = result/self.rating_num
		return "%g" % round(result, 1)

	def rating_int(self):
		result = float(self.cumulative_score)
		if self.rating_num == 0:
			return 0
		result = result/self.rating_num
		return int(round(result))

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('recipe_detail', (), {'pk': self.id})

	class Meta:
		ordering = ['-view_num', '-like_num']


class DidRecipe(models.Model):
	"""docstring for DidRecipe"""
	recipe = models.ForeignKey(Recipe)
	user = models.ForeignKey(User)
	image = ProcessedImageField(upload_to=did_get_file_path, null=True, blank=True, verbose_name=u'Cover image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 90})
	comment = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return u"%s's %s" % (self.user.username, self.recipe.name)

	@models.permalink
	def get_absolute_url(self):
		return ('did_recipe_detail', (), {'pk': self.id})

	class Meta:
		ordering = ['recipe', '-date']

class Amount(models.Model):
	"""docstring for Amount"""
	
	ingredient = models.ForeignKey(Food)
	recipe = models.ForeignKey(Recipe)
	amount = models.CharField(max_length=50)
	must = models.BooleanField(default=False)

	def __unicode__(self):
		return u'Amount of %s in %s' % (self.ingredient.name, self.recipe.name)

	class Meta:
		ordering = ['recipe','-must']
		unique_together = ('recipe', 'ingredient')
		
class Step(models.Model):
	"""docstring for Steps"""

	recipe = models.ForeignKey(Recipe)
	step_num = models.PositiveIntegerField()
	description = models.CharField(max_length = 1000)
	step_image = ProcessedImageField(upload_to=get_file_path, null=True, blank=True, verbose_name=u'Step image',
						processors=[Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFit(width=540,upscale=True)], format='JPEG', options={'quality': 80})

	def __unicode__(self):
		return u'Step %d of %s' % (self.step_num, self.recipe.name)

	class Meta:
		ordering = ['recipe', 'step_num']
		unique_together = ("recipe", "step_num")

class Vote(models.Model):
	"""Vote class, used for recommendation system """
	recipe = models.ForeignKey(Recipe)
	user = models.ForeignKey(User)
	score = models.PositiveSmallIntegerField(validators=[MaxValueValidator(5)])
	comment = models.TextField()
	date = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return u'Vote for %s from %s' %(self.recipe.name, self.user)

	class Meta:
		ordering = ['user', 'recipe',]
		unique_together = ("user", "recipe")

templates/autocomplete.html
{% load url from future %}
{% load thumbnail %}
{% load i18n %}

<div id="searchresults">
	{% if recipe_list %}
	<span class="category">Recipe</span>
		{% for recipe in recipe_list %}
		<a href="{{ recipe.get_absolute_url }}">
			<img alt="{{recipe.name}} image" src="{{ recipe.cover_image|thumbnail_url:'avatar' }}" style="height:50px; width:50px;" />
			<span class="searchheading">{{recipe.name|title}}</span>
			<span>{{recipe.brief|truncatechars:100}}</span>
		</a>
		{% endfor %}
	{% endif %}
	{% if food_list %}
	<span class="category">Food</span>

		{% for food in food_list %}
		<a href="{{ food.get_absolute_url }}">
			<img alt="{{food.name}} image" src="{{ food.cover_image|thumbnail_url:'avatar' }}" style="height:50px; width:50px;" />
			<span class="searchheading">{{food.name|title}}</span>
			<span>{{food.brief|truncatechars:100}}</span>
		</a>
		{% endfor %}
	{% endif %}
	<!-- more categories -->
	<span class="seperator">
		<a href="{% url 'hot_recipes'%}">More Hot Recipes</a>
	</span>
</p>

templates/base.html
<!-- skeleton code for using bootstrap in html -->
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="iDo">
    {% block meta %}{% endblock %}

    <title> {% block title %} {% endblock title %} - HallWay </title>

    <!-- Le styles de bootstrap -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "css/base.css" %}" type="text/css" />

    <!-- Google Font Lib -->
    <link href='http://fonts.googleapis.com/css?family=Dancing+Script:700,400' rel='stylesheet' type='text/css'>
    
    <!-- Your own css file -->
    <style type="text/css">{% block css %} {% endblock css %}</style>

    <!-- js files -->
    <script src="{% static "js/jquery-1.8.2.min.js" %}"></script>

    {% block csslink %} {% endblock csslink %}
    {% block js-head %} {% endblock js-head %}
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="some icon" href="{% static 'ico/favicon.ico' %}" />
    {% block icon %} {% endblock icon %}
  </head>

  <body style="min-width:995px;">
    {% block navbar %}{% endblock %}
    <div class="container">
        {% block content_title %}{% endblock %}
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.tinyscrollbar.min.js" %}"></script>
    {% block js %}{% endblock %}
    <script>console.log(window.innerWidth);</script>
  </body>
</html>

templates/index.html
{% extends 'nav.html' %}

{% load static from staticfiles %}
{% load url from future %}

{% load thumbnail %}

{% block csslink %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "css/bgstretcher.css" %}" type="text/css" />
  <link href='http://fonts.googleapis.com/css?family=Chela+One' rel='stylesheet' type='text/css' />
  <style type="text/css">
  @font-face {
      font-family: "Ribeye";
      src: url('/static/font/RibeyeMarrow-Regular.ttf');
  }
  .ribeye {
      font-family: "Ribeye";
  }
  </style>
{% endblock %}

{% block title %}
Welcome
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="login-modal">
  <div class="logbar">
    <div class="logbar-sign">
      {% if user.is_authenticated %}
        <a href="{% url 'userena_profile_detail' user.username %}"><i class="icon-user"></i></a>
      {% else %}
        <a href="#" data-toggle="modal"><i class="icon-user"></i></a>
      {% endif %}
    </div>
    <div class="logbar-content">
      {% if user.is_authenticated %}
      <a href="{% url 'userena_profile_detail' user.username %}#prof" id="u-profile"><i class="icon-file"></i> My Profile</a><br />
      <a href="{% url 'userena_profile_detail' user.username %}" id="u-recipe"><i class="icon-glass"></i> My Recipes</a><br />
      <a href="{% url 'userena_signout' %}" id="u-signout"><i class="icon-signout"></i> Sign Out</a>
      {% else %}
      <a data-toggle="modal" href="#signinModal" id="u-signin"><i class="icon-signin"></i> Sign In</a><br />
      <a data-toggle="modal" href="{% url 'userena_signup' %}" id="u-signout"><i class="icon-plus"></i> Sign Up</a><br />
      {% endif %}
    </div>
  </div>
  <div class="modal hide fade" tabindex="-1" aria-hidden="true" id="signinModal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">x</button>
      <legend>Sign In</legend>
    </div>
    <div class="modal-body">
      <form method="post" action="{% url 'userena_signin' %}" >
        {% csrf_token %}
        <fieldset>
          <img src="{% static 'img/welcome_pig.jpg' %}" id="welcomePig"/>
          <p><input type="text" class="span3" name="identification" id="email" placeholder="Username or Email"></p>
          <p><input type="password" class="span3" name="password" placeholder="Password"></p>
          <p class="checkbox">
            <label for="id_remember_me"><input type="checkbox" name="remember_me" id="id_remember_me" /> Remember me for a month</label>
          </p>
          <p><button type="submit" class="btn btn-primary">Sign in</button>
            <a href="{% url 'userena_password_reset' %}">Forgot Password?</a>
          </p>
        </fieldset>
      </form>
    </div>
    <div class="modal-footer">
      New To MyWebsite.com?
      <a href="{% url 'userena_signup' %}" class="btn btn-primary">Sign Up</a>
    </div>
  </div>
</div>
<div class="logo">
  <div class="ribeye">
    <div style="color: white; position: fixed; top: 20%; left: 50%; margin-left: -96.5px; font-size: 250%; font-weight: bold;">HALLWAY</div>
    <div style="color: white; position: fixed; top: 25%; left: 50%; margin-left: -145.5px; font-size: 150%;">to enjoyable foods and life</div>
  </div>
</div>
<div class="circular-show-outer upper-level">
  <ul class="circular-show-inner upper-level">
    <li class="show-item" id="courses">
      <a href="#">
        <div class="show-img upper" style="background-position: -250px;"></div>
        <div class="show-caption">Courses</div>
      </a>
    </li>
    <li class="show-item" id="cuisines">
      <a href="#">
        <div class="show-img upper" style="background-position: -550px;"></div>
        <div class="show-caption">Cuisines</div>
      </a>
    </li>
    <li class="show-item" id="sources">
      <a href="#">
        <div class="show-img upper" style="background-position: -1450px;"></div>
        <div class="show-caption">Sources</div>
      </a>
    </li>
    <li class="show-item" id="diets">
      <a href="#">
        <div class="show-img upper" style="background-position: -850px;"></div>
        <div class="show-caption">Diets</div>
      </a>
    </li>
    <li class="show-item hot" id="hot">
      <a href="{% url 'hot_recipes' %}">
        <div class="show-img upper" style="background-position: -1150px;"></div>
        <div class="show-caption">Hot!</div>
      </a>
    </li>
  </ul>
</div>
<div class="circular-show-outer lower-level">
  <ul class="circular-show-inner lower-level" data-target="courses">
    {% for c in Courses %}
      <li class="show-item" data-target="courses">
        <a href="{{c.get_absolute_url}}">
          <div class="show-img lower courses"></div>
          <div class="show-caption lower">{{c.name}}</div>
        </a>
      </li>
    {% endfor %}
  </ul>
  <ul class="circular-show-inner lower-level" data-target="cuisines">
    {% for c in Cuisines %}
      <li class="show-item" data-target="cuisines">
        <a href="{{c.get_absolute_url}}">
          <div class="show-img lower cuisines"></div>
          <div class="show-caption lower">{{c.name}}</div>
        </a>
      </li>
    {% endfor %}
  </ul>
  <ul class="circular-show-inner lower-level" data-target="sources">
    {% for c in Main_Ingredients %}
      <li class="show-item" data-target="sources">
        <a href="{{c.get_absolute_url}}">
          <div class="show-img lower sources"></div>
          <div class="show-caption lower">{{c.name}}</div>
        </a>
      </li>
    {% endfor %}
  </ul>
  <ul class="circular-show-inner lower-level" data-target="diets">
    {% for c in Special_Diets %}
      <li class="show-item" data-target="diets">
        <a href="{{c.get_absolute_url}}">
          <div class="show-img lower diets"></div>
          <div class="show-caption lower">{{c.name}}</div>
        </a>
      </li>
    {% endfor %}
  </ul>
  {# circular show nav #}
  <a class="show-control" href="#courses" id="pItem" style="display:none;"><i class="icon-chevron-left"></i></a>
  <a class="show-control" href="#courses" id="nItem" style="display:none;"><i class="icon-chevron-right"></i></a>
  <a class="show-control" href="#cuisines" id="pItem" style="display:none;"><i class="icon-chevron-left"></i></a>
  <a class="show-control" href="#cuisines" id="nItem" style="display:none;"><i class="icon-chevron-right"></i></a>
  <a class="show-control" href="#sources" id="pItem" style="display:none;"><i class="icon-chevron-left"></i></a>
  <a class="show-control" href="#sources" id="nItem" style="display:none;"><i class="icon-chevron-right"></i></a>
  <a class="show-control" href="#diets" id="pItem" style="display:none;"><i class="icon-chevron-left"></i></a>
  <a class="show-control" href="#diets" id="nItem" style="display:none;"><i class="icon-chevron-right"></i></a>
</div>

  <div id="bg-show"></div>
  <div class="content search-form">
    <form id="searchform" class="form-search" action="{% url 'normal_search' %}" method="POST">
      {% csrf_token %}
      <div id="suggestions"></div>
      <div class="search-div">
        <span class="search-icon"><i class="icon-search"></i></span>
        <input class="span5 search-query" id="searchinput" placeholder="Type in a dish name or the main ingredient..." type="search" autocomplete="off">
      </div>
      
    </form>
  </div>
  <div id="search_results"></div>
  
{% endblock %}

{% block js-head %}
  <script src="{% static "js/modernizr.custom.17475.js" %}"></script>
  <script src="{% static "js/bgstretcher.js" %}"></script>
  <script type="text/javascript">
  var j = jQuery.noConflict();
  j(document).ready(function(){
    j('#courses').find('a').tooltip({
      title: 'Browse Recipes by Courses',
      placement: 'top',
    });
    j('#cuisines').find('a').tooltip({
      title: 'Browse Recipes by Cuisines',
      placement: 'top',
    });
    j('#sources').find('a').tooltip({
      title: 'Browse Recipes by Main Ingredient',
      placement: 'top',
    });
    j('#diets').find('a').tooltip({
      title: 'Browse Special Diets Recipe',
      placement: 'top',
    });
    j('#hot').find('a').tooltip({
      title: 'Browse Our Most Populart Recipes',
      placement: 'top',
    });

    // initialize slider
    j('#bg-show').bgStretcher({
      images: ['/media/Index_Images/bg-img1.jpg', '/media/Index_Images/bg-img2.jpg',
                '/media/Index_Images/bg-img3.jpg','/media/Index_Images/bg-img4.jpg',
                '/media/Index_Images/bg-img5.jpg'],
      imageWidth: 1024, 
      imageHeight: 768, 
      slideDirection: 'N',
      nextSlideDelay: 7000,
      slideShowSpeed: 3000,
      slideShow: 'true',
      transitionEffect: 'fade',
      sequenceMode: 'normal',
      buttonPrev: '#prev',
      buttonNext: '#next',
      pagination: '#nav',
      anchoring: 'left center',
      anchoringImg: 'left center'
    });

    // animation control
    // j('#toggleAnimation').unbind('click');
    // j('#toggleAnimation').click(function(){
    //   if (j(this).html() == "PAUSE"){
    //     j(this).html("RESUME");
    //     j('#bg-show').bgStretcher.pause();
    //   } else {
    //     j(this).html("PAUSE");
    //     j('#bg-show').bgStretcher.play();
    //   }
    // });
    var delay = (function(){
      var timer = 0;
      return function(callback, ms){
        clearTimeout (timer);
        timer = setTimeout(callback, ms);
      };
    })();

    var minlength = 3;
    j('#suggestions').hide();
    j('#searchinput').focusout(function (){
      j('#suggestions').fadeOut();
    });
    j('#searchinput').keyup(function(event) {
      delay(function(){
        if(event.which != 13) {
          var value = j('#searchinput').val(),
              url = '';
          if(value.length >= minlength) {
            var postdata = {'q': value, 'csrfmiddlewaretoken': '{{ csrf_token }}'}
            j.post(url, postdata,
              function(data) {
                j('#suggestions').fadeIn();
                j('#suggestions').empty().append(data);
              }
            );
          }
          else {
            j('#suggestions').fadeOut();
          }
        }
      }, 300);
    });

    j('#searchinput').keypress(function (event){
      if (event.which == 13){
        j('#searchform').submit();
      }
    });
    
    j('#searchform').submit(function(event) {
      event.preventDefault();
      var value = j('#searchinput').val(),
          url = j(this).attr('action');
      var postdata = {'q': value, 'csrfmiddlewaretoken': '{{ csrf_token }}'}
      if(value.length >= minlength) {
        j.post(url, postdata,
          function(data) {
            j('#search_results').fadeIn();
            j('#search_results').empty().append(data);
          }
        );
      }
      else {
        j('#search_results').fadeOut();
      }
    });

  });
</script>
{% endblock js-head%}

{% block js %}
  <script type="text/javascript" src="{% static "js/recipe/index.js" %}"></script>
{% endblock js %}

templates/terms_of_service.html
<p>By clicking the button, you agree to the terms below:</p>
<p>By using and accessing this website, http://cmpt470.csil.sfu.ca:8014 (collectively referred to as the "Site" or "Chief" in these Terms of Service), you ("you", "user" or, "end user") agree to these Terms of Service (collectively, the "Terms of Service" or "Agreement").</p>

<p>IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, IMMEDIATELY STOP ACCESSING THIS SITE.</p>

<p>You agree not to modify, copy, distribute, transmit, display, perform, reproduce, publish, license, transfer, create derivate work from, sell or re-sell any content or information obtained from or through the Site.</p>

<p><strong>Third-party Sites.</strong><br />The Site may contain links to other websites maintained by third-parties. These links are provided solely as a convenience and does not imply endorsement of, or association with, the party by Chief.</p>

<p><strong>Modifications to this Agreement.</strong><br />Chief reserves the right to change or modify any of the terms and conditions contained in this Agreement at any time. You acknowledge and agree that it is your responsibility to review the Site and these Terms of Service from time to time. Your continued use of the Site after such modifications to this Agreement will constitute acknowledgment of the modified Terms of Service and agreement to abide and be bound by the modified Terms of Service.</p>

<p><strong>Termination of Use.</strong><br />Chief shall have the right to immediately terminate or suspend, in its discretion, your access to all or part of the Site with or without notice for any reason.</p>

<p><strong>Limitation of Liability.</strong><br />In no event shall Chief or its affiliates be liable for any indirect, incidental, special, punitive damages or consequential damages of any kind, or any damages whatsoever arising out of or related to your use of the Site, the content and other information obtained therein.</p>

<p>Certain jurisdictions prohibit the exclusion or limitation of liability for consequential or incidental damages, thus the above limitations may not apply to you. </p>

<p><strong>Governing Law.</strong><br />Any disputes arising out of or related to these Terms of Service and/or any use by you of the Site shall be governed by the laws of the Canada, without regard to the conflicts of laws provisions therein.</p>

<p><strong>Date of Last Update.</strong><br />This agreement was last updated on October 31, 2012.</p>

<p>Published with permission from <a href="http://termsfeed.com" title="Termsfeed">Termsfeed</a>.</p>

<style>
div.overview p {
	margin-left: 0;
	padding-left: 0;
}
</style>